// builtin_mods.cpp - the empty table a build without built-in plugins links.
// Kept in a fallback archive: the linker pulls it only when the host does not
// already define the table generated by cmake/BuiltinMods.cmake. This works
// on COFF too, without relying on ELF/Mach-O weak data replacement.
#include "builtin_mods.h"

extern const RecompBuiltinMod recomp_builtin_mods[] = {{nullptr, nullptr, nullptr, nullptr}};
